batch_size_per_gpu: 64
random_seed: 42

trainer:
  strategy: ddp_find_unused_parameters_true
  precision: "bf16-mixed" # choices: bf16-mixed, 32-true, 16-true
  max_epochs: 800
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  log_every_n_steps: 50
  check_val_every_n_epoch: 1
  val_check_interval: 1.0
  enable_checkpointing: true
  save_every_n_train_steps: 1000
  accumulate_grad_batches: 1
