name: billeh_v1
T: 96
num_classes: 2
in_channels: 1

# Billeh V1 backbone setup
billeh_data_dir: ./datasets/billeh/preprocessed/GLIF_network
n_neurons: 10000 # max=51798
full_core: false
train_v1: true
seed: 3407
# use_input_t: true
auto_n_input_from_in_channels: true

# image -> temporal input encoding for V1
encoding: poisson   # poisson | repeat
encoding_gain: 1.0
