name: billeh_v1
T: 200
num_classes: 10
in_channels: 1

# Billeh V1 backbone setup
billeh_data_dir: /data2/dataset/LGN_GLIF_Models/preprocessed/GLIF_network
n_input: 17400
n_neurons: 1000
full_core: false
train_v1: true
seed: 3407

# image -> temporal input encoding for V1
encoding: poisson   # poisson | repeat
encoding_gain: 1.0
