name: sequential_mnist
root: /data2/users/zhangjy/Training-data-driven-V1-model/data/mnist
num_classes: 10
is_event: true
num_workers: 4
pin_memory: true
val_ratio: 0.1
split_seed: 42
permute: false
permute_seed: 0
normalize_to_01: true
download: true
train_drop_last: false
